# Generated by Django 4.2.5 on 2023-12-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okommerce', '0010_alter_productcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('campaign_description', models.TextField()),
                ('campaign_image', models.ImageField(blank=True, null=True, upload_to='okommerz')),
            ],
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
