# Generated by Django 4.2.5 on 2023-12-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okommerce', '0012_product_description_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
