# Generated by Django 4.2.5 on 2023-11-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtemplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='enable_topbar',
            field=models.BooleanField(default=False),
        ),
    ]
