# Generated by Django 4.2.5 on 2023-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtemplate', '0002_topbar_enable_topbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('link', models.SlugField()),
            ],
        ),
    ]
