# Generated by Django 4.2.5 on 2023-12-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtemplate', '0003_headermenu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeaderMenu',
            new_name='Navbar',
        ),
        migrations.RenameField(
            model_name='navbar',
            old_name='text',
            new_name='menu',
        ),
    ]
