# Generated by Django 4.2.5 on 2023-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtemplate', '0004_rename_headermenu_navbar_rename_text_navbar_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='enabled',
            field=models.BooleanField(default=1),
        ),
    ]
