# Generated by Django 4.2.5 on 2023-12-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtemplate', '0006_alter_navbar_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
