# Generated by Django 4.2.5 on 2024-01-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtemplate', '0007_delete_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('JE', 'Journal Entry'), ('ICJE', 'Inter Company Journal Entry'), ('BE', 'Bank Entry'), ('CE', 'Cash Entry'), ('CCE', 'Credit Card Entry'), ('DN', 'Debit Note'), ('CN', 'Credit Note'), ('COE', 'Contra Entry'), ('EE', 'Excise Entry'), ('WOE', 'Write Off Entry'), ('OE', 'Opening Entry'), ('DE', 'Depreciation Entry'), ('ERR', 'Exchange Rate Revaluation'), ('EGOL', 'Exchange Gain Or Loss'), ('DR', 'Deferred Revenue'), ('DFE', 'Deferred Expense')], default='JE', max_length=255)),
                ('currency', models.CharField(choices=[('THB', 'THB'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('CAD', 'CAD')], default='THB', max_length=255)),
                ('currency_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Journal entry',
                'verbose_name_plural': 'Journal entries',
            },
        ),
    ]
