# Generated by Django 4.2.5 on 2023-10-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogList',
        ),
    ]
