# Generated by Django 4.2.5 on 2023-10-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogList',
            new_name='BlogPost',
        ),
    ]
