# Generated by Django 4.2.5 on 2023-11-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0006_blogcategory_alter_blogpost_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog categories'},
        ),
    ]
