# Generated by Django 4.2.5 on 2023-11-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0007_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='blogadmin.blogcategory'),
            preserve_default=False,
        ),
    ]
