# Generated by Django 4.2.5 on 2023-12-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogadmin', '0009_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='category',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
